import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import Header from "@/components/header";
import Spotlight from "@/components/spotlight";


export default function Home() {
  return (
    <>
      <Header />
      <div id="body-container" className={styles["body-container"]}>
        <Spotlight />
        <h1>Welcome to Renovy</h1>
        <p>
          At Renovy, we specialize in transforming old buildings into modern and classy homes. Our team of experienced professionals is dedicated to delivering high-quality workmanship and exceptional customer service. We take pride in our ability to preserve the unique character of historic buildings while incorporating contemporary design elements and state-of-the-art amenities.
        </p>
        <p>
          Our renovation services include:
        </p>
        <ul>
          <li>Comprehensive structural assessments and repairs</li>
          <li>Modernizing electrical, plumbing, and HVAC systems</li>
          <li>Custom interior and exterior design solutions</li>
          <li>Energy-efficient upgrades and sustainable building practices</li>
          <li>Restoration of historical features and architectural details</li>
        </ul>
        <p>
          We understand that every project is unique, and we work closely with our clients to ensure their vision is brought to life. From initial consultation to project completion, we are committed to exceeding expectations and delivering results that stand the test of time.
        </p>
        <p>
          Choose Renovy for your next renovation project and experience the perfect blend of tradition and innovation. Let us help you create a home that is not only beautiful but also functional and sustainable for years to come.
        </p>
      </div>
    </>
  );
}















/* ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */

{/* <Head>
  <title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="icon" href="/favicon.ico" />
</Head>
<main className={`${styles.main} ${inter.className}`}>
  <div className={styles.description}>
    <p>
      Get started by editing&nbsp;
      <code className={styles.code}>pages/index.tsx</code>
    </p>
    <div>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        By{" "}
        <Image
          src="/vercel.svg"
          alt="Vercel Logo"
          className={styles.vercelLogo}
          width={100}
          height={24}
          priority
        />
      </a>
    </div>
  </div>

  <div className={styles.center}>
    <Image
      className={styles.logo}
      src="/next.svg"
      alt="Next.js Logo"
      width={180}
      height={37}
      priority
    />
  </div>

  <div className={styles.grid}>
    <a
      href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      className={styles.card}
      target="_blank"
      rel="noopener noreferrer"
    >
      <h2>
        Docs <span>-&gt;</span>
      </h2>
      <p>
        Find in-depth information about Next.js features and&nbsp;API.
      </p>
    </a>

    <a
      href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      className={styles.card}
      target="_blank"
      rel="noopener noreferrer"
    >
      <h2>
        Learn <span>-&gt;</span>
      </h2>
      <p>
        Learn about Next.js in an interactive course with&nbsp;quizzes!
      </p>
    </a>

    <a
      href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      className={styles.card}
      target="_blank"
      rel="noopener noreferrer"
    >
      <h2>
        Templates <span>-&gt;</span>
      </h2>
      <p>
        Discover and deploy boilerplate example Next.js&nbsp;projects.
      </p>
    </a>

    <a
      href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      className={styles.card}
      target="_blank"
      rel="noopener noreferrer"
    >
      <h2>
        Deploy <span>-&gt;</span>
      </h2>
      <p>
        Instantly deploy your Next.js site to a shareable URL
        with&nbsp;Vercel.
      </p>
    </a>
  </div>
</main> */}